// @todo: export default type
export type CodeLanguage =
    | 'C++'
    | 'C'
    | 'C#'
    | 'JSON'
    | 'JavaScript'
    | 'JavaScriptXML'
    | 'TypeScript'
    | 'TypeScriptXML'
    | 'Python'
    | 'Lua'
    | 'XML'
    | 'HTML'
    | 'CSS'
    | 'SCSS'
    | 'SASS'
    | 'PHP'
    | 'LLVM'
    | 'BASIC'
    | 'PHP'
    | 'L0'
    | 'Haskell'
    | 'Kotlin'
    | 'Assembler'
