const s = require(`../../server/documenting`).shortcuts;


exports = module.exports = s.illustration( ...[
    s.sentence(`Ось що про нашу проблему думає C#.`),
    s.cs(
        [ `// шаблон для імітації розумних вказівників` ],
        [ `class shared_ptr<T> {}` ],
        [ `` ],
        [ `// Класи для пирогів` ],
        [ `class Pie {}` ],
        [ `class CinnamonPie: Pie {}` ],
        [ `` ],
        [ `// "інтерфейс" для пекаря` ],
        [ `abstract class Baker` ],
        [ `{` ],
        [ `    public abstract shared_ptr<Pie> Bake();` ],
        [ `}` ],
        [ `` ],
        [ `// проміжний клас для обходу обмежень мови` ],
        [ `class IntermediateCinnamonBaker: Baker` ],
        [ `{` ],
        [ `    // заміщуємо віртуальний метод` ],
        [ `    public override shared_ptr<Pie> Bake()` ],
        [ `    {` ],
        [ `        return new shared_ptr<Pie>();` ],
        [ `    }` ],
        [ `}` ],
        [ `` ],
        [ `// реалізація "корицевого" пекаря` ],
        [ `class CinnamonBaker: IntermediateCinnamonBaker` ],
        [ `{` ],
        [ `    // перекриваємо віртуальний метод` ],
        [ `    public new shared_ptr<CinnamonPie> Bake()` ],
        [ `    {` ],
        [ `        return new shared_ptr<CinnamonPie>();` ],
        [ `    }` ],
        [ `}` ],
    ),
]);
